# Generated by Django 4.1.6 on 2023-03-31 04:08

from django.db import migrations

def populate_db(apps, schema_editor):
    Conversion = apps.get_model('unitconv', 'Conversion')

    Conversion(unit="T", conversion=1).save()
    Conversion(unit="g", conversion=907200).save()
    Conversion(unit="t_oz", conversion=29170).save()
    Conversion(unit="kg", conversion=907.2).save()
    Conversion(unit="lb", conversion=2000).save()
    Conversion(unit="oz", conversion=32000).save()


class Migration(migrations.Migration):
    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
